print('Please enter on of these options: \nOneday, Twoday, Garnish, newtaxID, Cancel')
#x = input()

Oneday="Hi [Admin's Name], I hope you’re doing well! I just wanted to check in on this case, as I haven’t heard back from you yet. \nLet me know if you have any questions in regards to my last message— I’ll be happy to help! \nLooking forward to your reply,\n"
Twoday="Hi [Admin’s Name], \nI hope you’re doing well! I haven’t heard back from you on this thread, so I’m going to close this case for now. \nDon’t worry-- if you do have further questions or information to provide on the matter, you can certainly still reply to this thread and the case will be automatically reopened! \nWishing you a lovely day; let me know if I can help further. Best, Kev"
Cancel="Hi [ADMIN’S NAME], \nThanks for reaching out about closing down the [COMPANY NAME] account. We will be sad to see you go, but understand the desire to switch over to a different payroll service. No phone call is required to cancel your company’s Gusto account as I have enabled the ability to self cancel on your end. At your earliest convenience, please complete these additional steps in order to finalize the cancellation of your Gusto account:\nSign in to Gusto. \nClick the Settings tab. \nClick the Plan & Billing tab. \nClick Cancel Account under your Monthly Plan. \nYour previous answers will pre-populate in this 1st step. \nClick Continue. \nIndicate your desired election for how any outstanding tax payment(s) and/or quarterly filings should be handled. \nType in the company name as listed above the text box in Red. Use exact capitalization and spacing. \nCheck all boxes to acknowledge the statements associated with the cancellation elections made. \nClick Cancel Account. \n(Please complete these steps at your earliest convenience as the account will remain active until then.) Your final invoice will be for the month you entered the suspension or for the month of your last check date, whichever is later. Any pending payrolls that have already been processed with check dates in the future will impact the month of your last check date. If you have any additional questions or concerns, please don't hesitate to reach back out. I'd be happy to assist you with them."
Garnish="You can deduct a post-tax amount from your employee's paycheck to account for a wage garnishment or other debt. This money will stay in your company bank account, and if you have been ordered to remit it to any agencies, that will be your responsibility. Follow these steps: \nClick the People tab. \nClick your employee's name. \nClick +Add a Garnishment or Custom Deduction. \nSelect if this is a garnishment or custom deduction (post-tax). \nIf you're adding a child support garnishment, we'll pay the collecting agency on your behalf. Please reference this article to help you set up a child support garnishment. \nFor all other garnishments select the type from the dropdown menu. For custom deductions, enter a description which will appear on the employee's paystub. \nWe'll make these deductions from payroll and leave the money in your company account to pay directly to the collecting agency. \nSelect if this a recurring or one-time post-tax deduction. \nEnter the post-tax deduction amount for each payroll: \nDollar amount per pay period \nPercentage of disposable income, in which you can also add a maximum dollar amount per pay period \nFor recurring post-tax deductions, add an annual maximum if applicable. \nClick Save. \n\nThe next time you run payroll, this amount will be deducted from your employee's wages post-tax. The deduction will be seen as a separate line item on the employee's paystub. \nIf you've received a wage garnishment notice or income withholding order and have questions about it, contact the agency that sent you the notice or your accounting professional for more information. "
newtaxID="Clearing Tax ID:\n\nThanks for reaching out to Gusto. Kev here to help.\n\nI am able to clear out the current value so that you can re-enter this information into Gusto.\nWould you please provide the following so I may assist.\n(1) Company Name\n(2) State\n\nWith that information I can clear out any current value so you may refill it with the correct one. "


#print(oneday)
